version: "3.5"
networks:
  default:
    name: chouette

services:
  redis:
    image: redis:5.0.5

  chouette:
    build: .
    links:
      - redis
    environment:
      - API_KEY=sdgdsgs
      - CHOUETTE_TAGS={"saasf":"asfsa"}
      - COLLECTOR_PLUGINS=["host"]
    command: bash
